"""initial_schema

Revision ID: 583a06ebea3b
Revises:
Create Date: 2026-03-31 02:56:29.213753

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '583a06ebea3b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('adapter_class', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column(
        'body_tsv', postgresql.TSVECTOR(),
        sa.Computed("to_tsvector('portuguese', body)", persisted=True),
        nullable=True,
    ),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('organ', sa.String(length=255), nullable=True),
    sa.Column('act_type', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('raw_pdf_key', sa.Text(), nullable=True),
    sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_publications_organ', 'publications', ['organ'], unique=False)
    op.create_index(
        'idx_publications_source_date', 'publications',
        ['source_id', sa.literal_column('published_at DESC')], unique=False,
    )
    op.create_index(
        'idx_publications_tsv', 'publications',
        ['body_tsv'], unique=False, postgresql_using='gin',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_publications_tsv', table_name='publications', postgresql_using='gin')
    op.drop_index('idx_publications_source_date', table_name='publications')
    op.drop_index('idx_publications_organ', table_name='publications')
    op.drop_table('publications')
    op.drop_table('sources')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
